defmodule VagasUniversitarias.Repo.Migrations.AddAuthenticationResourcesAndAddPasswordAuthenticationAndAddPasswordAuth do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:vagas, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :titulo, :text, null: false
      add :pdf, :text
      add :salario_centavos, :bigint
      add :tipo, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :empresa_id, :uuid, null: false
    end

    create table(:vaga_tags, primary_key: false) do
      add :vaga_id,
          references(:vagas,
            column: :id,
            name: "vaga_tags_vaga_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :tag_id, :uuid
    end

    alter table(:users) do
      add :role, :text, null: false, default: "user"
      add :hashed_password, :text
      add :confirmed_at, :utc_datetime_usec
    end

    create table(:user_profiles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :full_name, :text
      add :nick_name, :text, null: false
      add :bio, :text, null: false
      add :avatar_url, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "user_profiles_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:user_profiles, [:user_id], name: "user_profiles_user_id_unique_index")

    create table(:tags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:vaga_tags) do
      modify :tag_id,
             references(:tags,
               column: :id,
               name: "vaga_tags_tag_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:tags) do
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:empresas, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:vagas) do
      modify :empresa_id,
             references(:empresas,
               column: :id,
               name: "vagas_empresa_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:empresas) do
      add :nome, :text, null: false
      add :logo_url, :text, null: false, default: "/images/empresa_logo_placeholder.png"
      add :likes, :bigint, null: false, default: 0
      add :descricao, :text, default: "Descrição não fornecida."

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:empresas) do
      remove :updated_at
      remove :inserted_at
      remove :descricao
      remove :likes
      remove :logo_url
      remove :nome
    end

    drop constraint(:vagas, "vagas_empresa_id_fkey")

    alter table(:vagas) do
      modify :empresa_id, :uuid
    end

    drop table(:empresas)

    alter table(:tags) do
      remove :updated_at
      remove :inserted_at
      remove :name
    end

    drop constraint(:vaga_tags, "vaga_tags_tag_id_fkey")

    alter table(:vaga_tags) do
      modify :tag_id, :uuid
    end

    drop table(:tags)

    drop_if_exists unique_index(:user_profiles, [:user_id],
                     name: "user_profiles_user_id_unique_index"
                   )

    drop constraint(:user_profiles, "user_profiles_user_id_fkey")

    drop table(:user_profiles)

    alter table(:users) do
      remove :confirmed_at
      remove :hashed_password
      remove :role
    end

    drop constraint(:vaga_tags, "vaga_tags_vaga_id_fkey")

    drop table(:vaga_tags)

    drop table(:vagas)
  end
end
