defmodule VagasUniversitarias.Repo.Migrations.MigrateResources14 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:vaga_tags, primary_key: false) do
      add :vaga_id,
          references(:vagas,
            column: :id,
            name: "vaga_tags_vaga_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :tag_id, :uuid
    end

    create table(:tags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:vaga_tags) do
      modify :tag_id,
             references(:tags,
               column: :id,
               name: "vaga_tags_tag_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:tags) do
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:tags) do
      remove :updated_at
      remove :inserted_at
      remove :name
    end

    drop constraint(:vaga_tags, "vaga_tags_tag_id_fkey")

    alter table(:vaga_tags) do
      modify :tag_id, :uuid
    end

    drop table(:tags)

    drop constraint(:vaga_tags, "vaga_tags_vaga_id_fkey")

    drop table(:vaga_tags)
  end
end
