defmodule VagasUniversitarias.Repo.Migrations.MigrateResources9 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:profile_notifications, primary_key: false) do
      add :user_id,
          references(:users,
            column: :id,
            name: "profile_notifications_user_id_fkey",
            type: :uuid,
            prefix: "public"
          )

      add :notification_id, :uuid
    end

    create table(:notifications, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:profile_notifications) do
      modify :notification_id,
             references(:notifications,
               column: :id,
               name: "profile_notifications_notification_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:notifications) do
      add :message, :text, null: false
      add :read, :boolean, default: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:notifications) do
      remove :updated_at
      remove :inserted_at
      remove :read
      remove :message
    end

    drop constraint(:profile_notifications, "profile_notifications_notification_id_fkey")

    alter table(:profile_notifications) do
      modify :notification_id, :uuid
    end

    drop table(:notifications)

    drop constraint(:profile_notifications, "profile_notifications_user_id_fkey")

    drop table(:profile_notifications)
  end
end
