defmodule VagasUniversitarias.Repo.Migrations.MigrateResources17 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:empresas) do
      modify :logo_url, :text, default: "/images/empresa_logo_placeholder.png"
    end
  end

  def down do
    alter table(:empresas) do
      modify :logo_url, :text, default: "https://via.placeholder.com/150"
    end
  end
end
