defmodule VagasUniversitarias.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:vagas) do
      add :pdf, :text
    end
  end

  def down do
    alter table(:vagas) do
      remove :pdf
    end
  end
end
