defmodule VagasUniversitarias.Repo.Migrations.MigrateResources15 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:empresas) do
      add :descricao, :text, default: "Descrição não fornecida."
    end
  end

  def down do
    alter table(:empresas) do
      remove :descricao
    end
  end
end
