defmodule VagasUniversitarias.Repo.Migrations.MigrateResources7 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:vagas) do
      add :salario_centavos, :bigint
    end
  end

  def down do
    alter table(:vagas) do
      remove :salario_centavos
    end
  end
end
