defmodule VagasUniversitarias.Repo.Migrations.MigrateResources13 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_profiles) do
      add :avatar_url, :text, null: false
    end
  end

  def down do
    alter table(:user_profiles) do
      remove :avatar_url
    end
  end
end
