defmodule VagasUniversitarias.Repo.Migrations.MigrateResources11 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:user_profiles, [:user_id], name: "user_profiles_user_id_unique_index")
  end

  def down do
    drop_if_exists unique_index(:user_profiles, [:user_id],
                     name: "user_profiles_user_id_unique_index"
                   )
  end
end
