defmodule VagasUniversitarias.Repo.Migrations.MigrateResources5 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      add :likes, :bigint, default: 0
    end
  end

  def down do
    alter table(:posts) do
      remove :likes
    end
  end
end
