defmodule VagasUniversitarias.Repo.Migrations.MigrateResources10 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_profiles) do
      remove :avatar_url
      remove :bio
    end
  end

  def down do
    alter table(:user_profiles) do
      add :bio, :text
      add :avatar_url, :text
    end
  end
end
