defmodule VagasUniversitarias.Repo.Migrations.MigrateResources10 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:profile_notifications), :user_id, to: :user_profile_id

    drop constraint(:profile_notifications, "profile_notifications_user_id_fkey")

    alter table(:profile_notifications) do
      modify :user_profile_id,
             references(:user_profiles,
               column: :id,
               name: "profile_notifications_user_profile_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end

  def down do
    drop constraint(:profile_notifications, "profile_notifications_user_profile_id_fkey")

    alter table(:profile_notifications) do
      modify :user_profile_id,
             references(:users,
               column: :id,
               name: "profile_notifications_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    rename table(:profile_notifications), :user_profile_id, to: :user_id
  end
end
