defmodule VagasUniversitarias.Repo.Migrations.MigrateResources5 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:vagas) do
      add :empresa_id, :uuid, null: false
    end

    create table(:empresas, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:vagas) do
      modify :empresa_id,
             references(:empresas,
               column: :id,
               name: "vagas_empresa_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:empresas) do
      add :nome, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:empresas) do
      remove :updated_at
      remove :inserted_at
      remove :nome
    end

    drop constraint(:vagas, "vagas_empresa_id_fkey")

    alter table(:vagas) do
      modify :empresa_id, :uuid
    end

    drop table(:empresas)

    alter table(:vagas) do
      remove :empresa_id
    end
  end
end
