defmodule VagasUniversitarias.Repo.Migrations.MigrateResources11 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:profile_notifications), :notification_id, to: :notifications_id

    drop constraint(:profile_notifications, "profile_notifications_notification_id_fkey")

    alter table(:profile_notifications) do
      modify :notifications_id,
             references(:notifications,
               column: :id,
               name: "profile_notifications_notifications_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end

  def down do
    drop constraint(:profile_notifications, "profile_notifications_notifications_id_fkey")

    alter table(:profile_notifications) do
      modify :notifications_id,
             references(:notifications,
               column: :id,
               name: "profile_notifications_notification_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    rename table(:profile_notifications), :notifications_id, to: :notification_id
  end
end
